import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {
  AiFillLinkedin, 
  AiFillGithub,
} from "react-icons/ai";
import Image from 'next/image';
import ProfPhoto from '../public/profile-photo.png';
import GameBuddy from '../public/GameBuddy-Landing.png';
import IdleProduction from '../public/Idle-Production-Promo.png';
import TurbinePromo from '../public/Turbine-Promo.png';


export default function Home() {
  // tuna
  return (
    <div>
      <Head>
        <title>Cameron's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='px-10 md:px-20 lg:px-40 bg-gray-900'>
        <section className=''>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'> Cameron's Corner</h1>
            <ul className='flex items-center'>
              <li><a href='https://github.com/killacan' target='_blank' className='text-4xl'><AiFillGithub /></a></li>
              <li><a className='bg-gradient-to-r from-blue-800 to-cyan-700 hover:from-cyan-700 hover:to-blue-800 text-white px-4 py-2 rounded-md ml-8' target={'_blank'} href="https://www.linkedin.com/in/cameron-sands-a97183169/">LinkedIn</a></li>
            </ul>
          </nav>
          <div className='xl:flex xl:flex-row-reverse justify-center'>
            <div>
              <div className='text-center p-10'>
                <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'> Cameron Sands</h2>
                <h3 className='text-2xl py-2 md:text-3xl'> Developer and Designer</h3>
                <p className='text-md py-5 leading-8 text-gray-300 md:text-xl max-w-xl mx-auto'>
                  I am a<span className='text-teal-500'> fullstack software developer </span>
                  and below are my latest projects. Above and below are links 
                  to my Github and LinkedIn
                </p>
              </div>

              <div className='text-5xl flex justify-center gap-16 py-3 text-gray-200'>
                <a href='https://github.com/killacan' target='_blank'><AiFillGithub /></a>
                <a href='https://www.linkedin.com/in/cameron-sands-a97183169/' target='_blank'><AiFillLinkedin /></a>
              </div>
            </div>
            <div>
              {/* <div className='relative mx-auto mt-20' >
                <Image src={ProfPhoto} className='rounded-full w-80 h-80 mx-auto md:h-96 md:w-96' />

              </div> */}
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 w-32 hover:scale-110 duration-300 hover:text-teal-500'> Projects </h3>
            <p className='text-md py-2 leading-8 text-gray-300'>
              Here are some of my <span className='text-teal-500'> projects</span>, click on them to check them out.
            </p>
          </div>
          <div className='grid xl:grid-cols-3 xl:gap-10'>
            <div className='text-center shadow-lg border-2 p-10 rounded-xl my-5 hover:bg-slate-900 hover:scale-110 duration-300'>
              <Image src={GameBuddy} width={200} height={200} className='mx-auto' />
              <h3 className='text-lg font-medium pt-8 pb-2'>Game Buddy</h3>
              <p className='py-2'>
                Game Buddy is a web application that allows for people
                to discover new communities of gamers. Our project features
                a connection to the Riot API for stat verification in League
                of Legends. It also has a functioning websocket for real time
                chat communications.
              </p>
              <h4 className='py-4 text-teal-600'>Technologies Used</h4>
              <p className='text-gray-300 py-1'>React</p>
              <p className='text-gray-300 py-1'>Express</p>
              <p className='text-gray-300 py-1'>MongoDB</p>
              <p className='text-gray-300 py-1'>Node.js</p>
              <div className='flex justify-center overflow-visible'>
                <div className='py-2'><a className='bg-blue-600 text-white px-4 py-2 rounded-md mx-4 hover:px-6 hover:py-4 hover:mx-2' href='https://github.com/killacan/gameBuddy' target={'_blank'}>Source Code</a></div>
                <div className='py-2'><a className='bg-blue-600 text-white px-4 py-2 rounded-md mx-4 hover:px-6 hover:py-4 hover:mx-2' href='https://gamebuddy-app.herokuapp.com/' target={'_blank'}>Live Project</a></div>
              </div>
            </div>
            <div className='text-center shadow-lg border-2 p-10 rounded-xl my-5 hover:bg-slate-900 hover:scale-110 duration-300'>
              <Image src={IdleProduction} width={200} height={200} className='mx-auto' />
              <h3 className='text-lg font-medium pt-8 pb-2'>Idle Production</h3>
              <p className='py-2'>
                Idle Production is a fun idle game where you can build a massive factory. The game follows a 
                steady progression of upgraded buildings and increasing amounts of money. The game can be played 
                for basically ever. Eventually it will have a "win condition" after earning a certain amount. 
              </p>
              <h4 className='py-4 text-teal-600'>Technologies Used</h4>
              <p className='text-gray-300 py-1'>JavaScript</p>
              <p className='text-gray-300 py-1'>Node.js</p>
              <p className='text-gray-300 py-1'>Canvas</p>
              <p className='text-gray-300 py-1'>HTML5</p>
              <div className='flex justify-center overflow-visible'>
                <div className='py-2'><a className='bg-blue-600 text-white px-4 py-2 rounded-md mx-4 hover:px-6 hover:py-4 hover:mx-2' href='https://github.com/killacan/IdleProduction' target={'_blank'}>Source Code</a></div>
                <div className='py-2'><a className='bg-blue-600 text-white px-4 py-2 rounded-md mx-4 hover:px-6 hover:py-4 hover:mx-2' href='https://killacan.github.io/IdleProduction//' target={'_blank'}>Live Project</a></div>
              </div>
            </div>
            <div className='text-center shadow-lg border-2 p-10 rounded-xl my-5 hover:bg-slate-900 hover:scale-110 duration-300'>
              <Image src={TurbinePromo} width={230} height={200} className='mx-auto' />
              <h3 className='text-lg font-medium pt-8 pb-2'>Turbine</h3>
              <p className='py-2'>
                Turbine is a clone of steam with a working 
                user auth system, a cart for each user, and AWS hosting of all
                images to reduce server load. 
              </p>
              <h4 className='py-4 text-teal-600'>Technologies Used</h4>
              <p className='text-gray-300 py-1'>React</p>
              <p className='text-gray-300 py-1'>JavaScript</p>
              <p className='text-gray-300 py-1'>Redux</p>
              <p className='text-gray-300 py-1'>Ruby on Rails</p>
              <p className='text-gray-300 py-1'>PostgreSQL</p>
              <p className='text-gray-300 py-1'>Node.js</p>
              <div className='flex justify-center overflow-visible'>
                <div className='py-2'><a className='bg-blue-600 text-white px-4 py-2 rounded-md mx-4 hover:px-6 hover:py-4 hover:mx-2' href='https://github.com/killacan/TurbineFullStack' target={'_blank'}>Source Code</a></div>
                <div className='py-2'><a className='bg-blue-600 text-white px-4 py-2 rounded-md mx-4 hover:px-6 hover:py-4 hover:mx-2' href='https://steam-turbine.herokuapp.com/' target={'_blank'}>Live Project</a></div>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div className='py-4'>
            <h2 className='text-3xl py-1'>About <span className='text-teal-500'>me</span></h2>
            <p className='py-2'>Hello! I am Cameron Sands and I am a passionate <span className='text-teal-500'> fullstack software developer</span>.</p>
            <p className='py-2'>I have a passion for creating responsive, feature rich websites.</p>
            <p className='py-2'>If you would like to hire me, reach out on linkedIn or by email at cmsands@tutanota.com.</p>
          </div>
        </section>
        <nav className='py-10 flex justify-between'>
            <h1 className='text-xl'> Find me on LinkedIn or Github</h1>
            <ul className='flex items-center'>
              <li><a href='https://github.com/killacan' target='_blank' className='text-4xl'><AiFillGithub /></a></li>
              <li><a className='bg-gradient-to-r from-blue-800 to-cyan-700 hover:from-cyan-700 hover:to-blue-800 text-white px-4 py-2 rounded-md ml-8' target={'_blank'} href="https://www.linkedin.com/in/cameron-sands-a97183169/">LinkedIn</a></li>
            </ul>
          </nav>
      </main>


    </div>
  );
}
